wandb:
  group: weight-decay-adam-sweep 
  project: batch-size-sched
  name: 150m-adam
optimizer: 
  beta_0: 0.9
  beta_1: 0.95
  eps: 1.0e-8
  decouple_weight_decay: true 
  decay_norm_and_bias: true
  decay_embeddings: true
  metrics_log_interval: 100
sweep: # first are for altering bsz and lr same time, then separate
  - scheduler:
      name: ["cosine_with_warmup"]
      t_warmup: 3.3e8
      units: "tokens"
    global_train_batch_size: 512
    max_duration: 3.3e9T
    optimizer:
      name: adamw
      learning_rate: [3.0e-2]
      weight_decay: [1.0e-4, 1.0e-5, 1.0e-6]
  - scheduler:
      name: ["cosine_with_warmup"]
      t_warmup: 3.3e8
      units: "tokens"
    global_train_batch_size: 256
    max_duration: 3.3e9T
    optimizer:
      name: adamw
      learning_rate: [3.0e-2]
      weight_decay: [1.0e-4, 1.0e-5, 1.0e-6]
  - scheduler:
      name: ["cosine_with_warmup"]
      t_warmup: 3.3e8
      units: "tokens"
    global_train_batch_size: 128
    max_duration: 3.3e9T
    optimizer:
      name: adamw
      learning_rate: [3.0e-2]
      weight_decay: [1.0e-4, 1.0e-5, 1.0e-6]