# 1 jobs

device_train_microbatch_size: 64

wandb:
  group: sooptimizers-150-3
optimizer:
  weight_decay: 0.0
  max_precond_dim: 10000
  projection_type: "full"
  precondition_frequency: 100
  beta_1: 0.99
  shampoo_beta: -1
  eps: 1.0e-10
  beta_0: 0.95
scheduler:
  name: cosine_with_warmup
  t_warmup: 5000



sweep:
  #- optimizer:
  #    name: [stableradam]
  #    learning_rate: [1.0e-4, 3.16e-4, 1.0e-3, 3.16e-3, 1.0e-2]
  #    precondition_frequency: 10
  #    beta_1: 0.95
  - optimizer:
      name: [stableshampoo]
      #learning_rate: [3.16e-4, 1.0e-3, 3.16e-3, 1.0e-2, 3.16e-2]
      learning_rate: [1.0e-1]
  - optimizer:
      name: [stablershampoo]
      #learning_rate: [1.0e-4, 3.16e-4, 1.0e-3, 3.16e-3, 1.0e-2]
      learning_rate: [1.0e-4, 1.0e-2]

save_overwrite: true
save_interval: 1000000