# 4 jobs
sweep:
  - device_train_microbatch_size: 64
    wandb:
      group: decay-layers-1
    optimizer:
      name: adamw
      learning_rate: 1.0e-3
      decouple_weight_decay: true
      weight_decay: 1.0e-4
      decay_norm_and_bias: [true, false]
      decay_embeddings: [true, false]
      eps: 1.0e-15
      beta_0: 0.9
      beta_1: 0.95