# 54 jobs
wandb:
  group: optimizers-1b-1
# device_train_microbatch_size: 128
# max_duration: 100000 # 13.1B tokens / (256 batch * 512 context)
optimizer:
  weight_decay: 0.0
  eps: 1.0e-15
  beta_0: 0.9
  beta_1: 0.95
save_count_log_scale_unsharded: 10
save_num_unsharded_checkpoints_to_keep: 11
sweep:
  - optimizer:
      name: adamw
      learning_rate: [1.0e-4, 3.16e-4, 1.0e-3, 3.16e-3, 1.0e-2, 3.16e-2, 1.0e-1, 3.16e-1, 1.0]
  - optimizer:
      name: lionw
      learning_rate: [1.0e-5, 3.16e-5, 1.0e-4, 3.16e-4, 1.0e-3, 3.16e-3, 1.0e-2, 3.16e-2, 1.0e-1]
  - optimizer:
      name: signsgd
      learning_rate: [1.0e-5, 3.16e-5, 1.0e-4, 3.16e-4, 1.0e-3, 3.16e-3, 1.0e-2, 3.16e-2, 1.0e-1]
  - optimizer:
      name: adafactorw
      neuron_only: false
      learning_rate: [1.0e-4, 3.16e-4, 1.0e-3, 3.16e-3, 1.0e-2, 3.16e-2, 1.0e-1, 3.16e-1, 1.0]
  - optimizer: 
      name: novagradw # corrected novograd
      learning_rate: [1.0e-4, 3.16e-4, 1.0e-3, 3.16e-3, 1.0e-2, 3.16e-2, 1.0e-1, 3.16e-1, 1.0]
      att_correction: True
      lastlayer_correction: True
  - optimizer:
    #   name: sgdw
    #   beta_0: 0.98
    #   learning_rate: [1.0e-3, 3.16e-3, 1.0e-2, 3.16e-2, 1.0e-1, 3.16e-1, 1.0, 3.16, 10.0]
      name: sgdw
      use_dampening: true
      beta_0: 0.98
      learning_rate: [1.0e-1, 3.16e-1, 1.0, 3.16, 10.0, 31.6, 100.0, 316.0, 1000.0]    


       
  # - device_train_microbatch_size: 32
  #   optimizer:
  #     name: sophiag
  #     eps: 0.02
  #     hessian_interval: 10
  #     learning_rate: [3.16e-4, 1.0e-3, 3.16e-3, 1.0e-2, 3.16e-2, 1.0e-1, 3.16e-1, 1.0, 3.16]
