# 9 jobs
wandb:
  group: sophia-5
device_train_microbatch_size: 32
optimizer:
  weight_decay: 0.0
  eps: 0.02
  beta_0: 0.9
  beta_1: 0.95
  hessian_interval: 10
save_num_unsharded_checkpoints_to_keep: 0
sweep:
  - optimizer:
      name: sophiag
      learning_rate: [1.0e-4, 3.16e-4, 1.0e-3, 3.16e-3, 1.0e-2, 3.16e-2, 1.0e-1, 3.16e-1, 1.0, 3.16]